# -*- coding: utf-8 -*-

aircraftTypeTags = [
    "aerobatic",
    "airship",
    "balloon",
    "bizjet",
    "bomber",
    "cargo",
    "carrier",
    "fighter",
    "ga",
    "glider",
    "groundvehicle",
    "helicopter",
    "interceptor",
    "passenger",
    "racer",
    "spaceship",
    "tanker",
    "trainer",
    "transport",
    "ultralight",
    "unpowered",
    "uav",
    "reconnaissance",
    "seacraft",
    "crop-duster",
    "bush-plane"
]

manufacturerTags = [
    "airbus",
    "antonov",
    "arado",
    "atr",
    "avro",
    "bae",
    "bell",
    "bleriot",
    "boeing",
    "bombardier",
    "caudron",
    "cessna",
    "consolidated",
    "dassault",
    "diamond",
    "dornier",
    "douglas",
    "embraer",
    "eurocopter",
    "fairchild",
    "fairey",
    "focke-wulf",
    "fokker",
    "general-dynamics",
    "gotha",
    "grumman",
    "handley-page",
    "hawker",
    "heinkel",
    "ilyushin",
    "junkers",
    "kawasaki",
    "lockheed",
    "mc-donnell-douglas",
    "messerschmitt",
    "mikoyan-gurevich",
    "mitsubishi",
    "north-american",
    "northrop",
    "pilatus",
    "piper",
    "republic",
    "robin",
    "rockwell",
    "saab",
    "short",
    "sopwith",
    "spad",
    "sukhoi",
    "supermarine",
    "tupolev",
    "vickers",
    "vought",
    "wright",
    "yakovlev"
]

eraTags = [
    "1910s",
    "1920s",
    "1930s",
    "1940s",
    "1950s",
    "1960s",
    "1970s",
    "1980s",
    "1990s",
    "2000s",
    "2010s",
    "coldwar",
    "early-pioneers",
    "golden-age",
    "gulfwar1",
    "gulfwar2",
    "vietnam",
    "ww1",
    "ww2"
]

featureTags = [
    "aerobatic",
    "airship",
    "amphibious",
    "biplane",
    "canard",
    "castering-wheel",
    "combat",
    "delta",
    "etops",
    "experimental",
    "fictional",
    "fixed-gear",
    "floats",
    "glass-cockpit",
    "low-wing",
    "mid-wing",
    "high-wing",
    "h-tail",
    "hud",
    "ifr",
    "lifting-body",
    "pressurised",
    "prototype",
    "refuel",
    "retractable-gear",
    "seaplane",
    "skis",
    "stol",
    "supersonic",
    "supercharger",
    "t-tail",
    "tail-dragger",
    "tricycle",
    "tail-hook",
    "triplane",
    "twin-boom",
    "v-tail",
    "variable-geometry",
    "vtol",
    "wing-fold"
    "water-drop"
]

propulsionTags = [
    "afterburner",
    "diesel",
    "electric",
    "jet",
    "propeller",
    "piston",
    "radial",
    "rocket",
    "single-engine",
    "supercharged",
    "turboprop",
    "twin-engine",
    "four-engine",
    "variable-pitch",
    "fixed-pitch"
]

simFeatureTags = [
    "dual-controls",
    "rembrandt",
    "tow",
    "wildfire"
]

tags = (aircraftTypeTags + manufacturerTags + eraTags + simFeatureTags +
        propulsionTags + featureTags)

def isValidTag(maybeTag):
    return maybeTag in tags
